const dfeAnalyticsDataform = require("../");

dfeAnalyticsDataform({
    eventSourceName: "gse",
    bqProjectName: "get-into-teaching",
    bqDatasetName: "gse_events_production",
    bqEventsTableName: "events",
    urlRegex: "schoolexperience.education.gov.uk",
    expirationDays: false,
    hiddenPolicyTagLocation: "projects/get-into-teaching/locations/europe-west2/taxonomies/6582996680844371982/policyTags/3882815557042264125",
    compareChecksums: false,
    transformEntityEvents: true,
    enableWebRequestIdentityResolution: true,
    enableSessionDetailsTable: true,
    expirationDays: false, 
    dataSchema: [{
            entityTableName: "bookings_school_searches",
            description: "",
            dataFreshnessDays: 3,
            dataFreshnessDisableDuringRange: true,
            keys: [{
                keyName: "query",
                dataType: "string",
                description: "",
                hidden: true,
            }, {
                keyName: "location",
                dataType: "string",
                description: "",
                hidden: true,
            }, {
                keyName: "radius",
                dataType: "integer",
                description: ""
            }, {
                keyName: "subjects",
                dataType: "string",
                isArray: true,
                description: ""
            }, {
                keyName: "phases",
                dataType: "string",
                isArray: true,
                description: ""
            }, {
                keyName: "max_fee",
                dataType: "integer",
                description: ""
            }, {
                keyName: "page",
                dataType: "string",
                description: ""
            }, {
                keyName: "number_of_results",
                dataType: "integer",
                description: ""
            }, {
                keyName: "coordinates",
                dataType: "string",
                description: "",
                hidden: true,
            }, {
                keyName: "analytics_tracking_uuid",
                dataType: "string",
                description: ""
            }, {
                keyName: "dbs_policies",
                dataType: "string",
                description: ""
            }, {
                keyName: "disability_confident",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "parking",
                dataType: "boolean",
                description: ""
            }]
        },
        {
            entityTableName: "users",
            description: "",
            dataFreshnessDays: 5,
            dataFreshnessDisableDuringRange: true,
            hidePrimaryKey: true,
            keys: [{
                keyName: "sub",
                dataType: "string",
                description: "",
                hidden: true,
            }]
        },
        {
            entityTableName: "schools_on_boarding_profile_subjects",
            description: "",
            materialisation: "view",
            keys: [{
                keyName: "schools_school_profile_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "schools_school_profiles"
            }, {
                keyName: "bookings_subject_id",
                dataType: "string",
                description: ""
            }]
        },
        {
            entityTableName: "bookings_placement_request_cancellations",
            description: "",
            dataFreshnessDays: 3,
            dataFreshnessDisableDuringRange: true,
            keys: [{
                keyName: "bookings_placement_request_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_placement_requests"
            }, {
                keyName: "cancelled_by",
                dataType: "string",
                description: ""
            }, {
                keyName: "sent_at",
                dataType: "timestamp",
                description: ""
            }, {
                keyName: "viewed_at",
                dataType: "timestamp",
                description: ""
            }, {
                keyName: "rejection_category",
                dataType: "string",
                description: ""
            }, {
                keyName: "fully_booked",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "accepted_on_ttc",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "date_not_available",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "no_relevant_degree",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "no_phase_availability",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_not_local",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "duplicate",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "info_not_provided",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "cancelation_requested",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "wrong_choice_secondary",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "wrong_choice_primary",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "other",
                dataType: "boolean",
                description: ""
            }]
        }, {
            entityTableName: "schools_school_profiles",
            description: "",
            materialisation: "view",
            keys: [{
                keyName: "candidate_requirement_dbs_requirement",
                dataType: "string",
                description: ""
            }, {
                keyName: "candidate_requirement_dbs_policy",
                dataType: "string",
                description: ""
            }, {
                keyName: "candidate_requirement_requirements",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "fees_administration_fees",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "fees_dbs_fees",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "fees_other_fees",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "administration_fee_amount_pounds",
                dataType: "integer",
                description: ""
            }, {
                keyName: "administration_fee_interval",
                dataType: "string",
                description: ""
            }, {
                keyName: "administration_fee_payment_method",
                dataType: "string",
                description: ""
            }, {
                keyName: "dbs_fee_amount_pounds",
                dataType: "string",
                description: ""
            }, {
                keyName: "dbs_fee_interval",
                dataType: "string",
                description: ""
            }, {
                keyName: "dbs_fee_payment_method",
                dataType: "string",
                description: ""
            }, {
                keyName: "phases_list_primary",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "phases_list_secondary",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "phases_list_college",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "key_stage_list_early_years",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "key_stage_list_key_stage_1",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "key_stage_list_key_stage_2",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_dress_code_business_dress",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_dress_code_cover_up_tattoos",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_dress_code_remove_piercings",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_dress_code_smart_casual",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_dress_code_other_dress_requirements",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_parking_information_parking_provided",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_experience_detail_disabled_facilities",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_experience_schedule_start_time",
                dataType: "string",
                description: ""
            }, {
                keyName: "candidate_experience_schedule_end_time",
                dataType: "string",
                description: ""
            }, {
                keyName: "candidate_experience_schedule_times_flexible",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "teacher_training_provides_teacher_training",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "bookings_school_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_schools"
            }, {
                keyName: "phases_list_secondary_and_college",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "confirmation_acceptance",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "administration_fee_step_completed",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "other_fee_step_completed",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "dbs_requirement_requires_check",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "dbs_fee_step_completed",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_requirements_selection_on_teacher_training_course",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_requirements_selection_live_locally",
                dataType: "string",
                description: ""
            }, {
                keyName: "candidate_requirements_selection_maximum_distance_from_school",
                dataType: "string",
                description: ""
            }, {
                keyName: "candidate_requirements_selection_other",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "access_needs_support_supports_access_needs",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_requirements_selection_step_completed",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_requirements_selection_not_on_another_training_course",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_requirements_selection_has_or_working_towards_degree",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "disability_confident_is_disability_confident",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "access_needs_policy_has_access_needs_policy",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "candidate_requirements_selection_provide_photo_identification",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "dbs_requirement_dbs_policy_conditions",
                dataType: "string",
                description: ""
            }, {
                keyName: "candidate_dress_code_step_completed",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "other_fee_amount_pounds",
                dataType: "integer",
                description: ""
            }, {
                keyName: "other_fee_interval",
                dataType: "string",
                description: ""
            }, {
                keyName: "other_fee_payment_method",
                dataType: "string",
                description: ""
            }]
        },
        {
            entityTableName: "candidates_booking_feedbacks",
            description: "",
            dataFreshnessDays: 7,
            dataFreshnessDisableDuringRange: true,
            keys: [{
                keyName: "bookings_booking_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_bookings"
            }, {
                keyName: "gave_realistic_impression",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "covered_subject_of_interest",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "influenced_decision",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "intends_to_apply",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "effect_on_decision",
                dataType: "string",
                description: ""
            }]
        },
        {
            entityTableName: "bookings_subjects",
            description: "",
            materialisation: "view",
            keys: [{
                keyName: "name",
                dataType: "string",
                description: ""
            }, {
                keyName: "hidden",
                dataType: "string",
                description: ""
            }, {
                keyName: "secondary_subject",
                dataType: "string",
                description: ""
            }]
        },
        {
            entityTableName: "bookings_schools_subjects",
            description: "",
            materialisation: "view",
            keys: [{
                keyName: "bookings_school_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_schools"
            }, {
                keyName: "bookings_subject_id",
                dataType: "string",
                description: ""
            }]
        },
        {
            entityTableName: "bookings_schools_phases",
            description: "",
            materialisation: "view",
            keys: [{
                keyName: "bookings_school_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_schools"
            }, {
                keyName: "bookings_phase_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_phases"
            }]
        },
        {
            entityTableName: "bookings_school_types",
            description: "",
            materialisation: "view",
            keys: [{
                keyName: "name",
                dataType: "string",
                description: ""
            }, {
                keyName: "edubase_id",
                dataType: "string",
                description: ""
            }]
        },
        {
            entityTableName: "bookings_schools",
            description: "",
            dataFreshnessDays: 3,
            dataFreshnessDisableDuringRange: true,
            keys: [{
                keyName: "name",
                dataType: "string",
                description: ""
            }, {
                keyName: "fee",
                dataType: "integer",
                description: ""
            }, {
                keyName: "urn",
                dataType: "string",
                description: ""
            }, {
                keyName: "website",
                dataType: "string",
                description: ""
            }, {
                keyName: "address_1",
                dataType: "string",
                description: ""
            }, {
                keyName: "address_2",
                dataType: "string",
                description: ""
            }, {
                keyName: "address_3",
                dataType: "string",
                description: ""
            }, {
                keyName: "town",
                dataType: "string",
                description: ""
            }, {
                keyName: "county",
                dataType: "string",
                description: ""
            }, {
                keyName: "postcode",
                dataType: "string",
                description: ""
            }, {
                keyName: "bookings_school_type_id",
                dataType: "string",
                description: ""
            }, {
                keyName: "teacher_training_provider",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "teacher_training_website",
                dataType: "string",
                description: ""
            }, {
                keyName: "enabled",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "availability_preference_fixed",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "views",
                dataType: "integer",
                description: ""
            }, {
                keyName: "experience_type",
                dataType: "string",
                description: ""
            }, {
                keyName: "coordinates",
                dataType: "string",
                description: ""
            }]
        },
        {
            entityTableName: "bookings_profiles",
            description: "",
            materialisation: "view",
            keys: [{
                keyName: "school_id",
                dataType: "string",
                description: ""
            }, {
                keyName: "dbs_required",
                dataType: "string",
                description: ""
            }, {
                keyName: "dbs_policy",
                dataType: "string",
                description: ""
            }, {
                keyName: "individual_requirements",
                dataType: "string",
                description: ""
            }, {
                keyName: "primary_phase",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "secondary_phase",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "college_phase",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "key_stage_early_years",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "key_stage_1",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "key_stage_2",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "dress_code_business",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "dress_code_cover_tattoos",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "dress_code_remove_piercings",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "dress_code_smart_casual",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "disabled_facilities",
                dataType: "string",
                description: ""
            }, {
                keyName: "parking_provided",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "start_time",
                dataType: "string",
                description: ""
            }, {
                keyName: "end_time",
                dataType: "string",
                description: ""
            }, {
                keyName: "flexible_on_times",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "administration_fee_amount_pounds",
                dataType: "integer",
                description: ""
            }, {
                keyName: "administration_fee_interval",
                dataType: "string",
                description: ""
            }, {
                keyName: "administration_fee_payment_method",
                dataType: "string",
                description: ""
            }, {
                keyName: "dbs_fee_amount_pounds",
                dataType: "integer",
                description: ""
            }, {
                keyName: "dbs_fee_interval",
                dataType: "string",
                description: ""
            }, {
                keyName: "dbs_fee_payment_method",
                dataType: "string",
                description: ""
            }, {
                keyName: "other_fee_amount_pounds",
                dataType: "integer",
                description: ""
            }, {
                keyName: "other_fee_interval",
                dataType: "string",
                description: ""
            }, {
                keyName: "other_fee_payment_method",
                dataType: "string",
                description: ""
            }, {
                keyName: "dbs_requires_check",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "supports_access_needs",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "disability_confident",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "has_access_needs_policy",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "admin_contact_phone",
                dataType: "string",
                description: "The phone number of the schools admin contact",
                hidden: true
            }, {
                keyName: "admin_contact_email",
                dataType: "string",
                description: "",
                hidden: true
            }, {
                keyName: "admin_contact_email_secondary",
                dataType: "string",
                description: "",
                hidden: true
            }]
        },
        {
            entityTableName: "bookings_placement_date_subjects",
            description: "",
            dataFreshnessDays: 28,
            dataFreshnessDisableDuringRange: true,
            keys: [{
                keyName: "bookings_placement_date_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_placement_dates"
            }, {
                keyName: "bookings_subject_id",
                dataType: "string",
                description: ""
            }]
        },
        {
            entityTableName: "bookings_placement_dates",
            description: "",
            dataFreshnessDays: 7,
            dataFreshnessDisableDuringRange: true,
            keys: [{
                keyName: "date",
                dataType: "date",
                description: ""
            }, {
                keyName: "duration",
                dataType: "integer",
                description: ""
            }, {
                keyName: "active",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "bookings_school_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_schools"
            }, {
                keyName: "max_bookings_count",
                dataType: "integer",
                description: ""
            }, {
                keyName: "published_at",
                dataType: "timestamp",
                description: ""
            }, {
                keyName: "subject_specific",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "supports_subjects",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "virtual",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "end_availability_offset",
                dataType: "integer",
                description: ""
            }, {
                keyName: "start_availability_offset",
                dataType: "integer",
                description: ""
            }, {
                keyName: "recurring",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "publishable",
                dataType: "boolean",
                description: ""
            }]
        },
        {
            entityTableName: "bookings_phases",
            description: "",
            materialisation: "view",
            keys: [{
                keyName: "name",
                dataType: "string",
                description: ""
            }, {
                keyName: "position",
                dataType: "string",
                description: ""
            }, {
                keyName: "edubase_id",
                dataType: "string",
                description: ""
            }, {
                keyName: "supports_subjects",
                dataType: "string",
                description: ""
            }]
        },
        {
            entityTableName: "bookings_candidates",
            description: "",
            dataFreshnessDays: 3,
            dataFreshnessDisableDuringRange: true,
            hidePrimaryKey: true,
            keys: [{
                    keyName: "confirmed_at",
                    dataType: "timestamp",
                    description: ""
                }, {
                    keyName: "created_in_gitis",
                    dataType: "boolean",
                    description: ""
                },
                {
                    keyName: "gitis_uuid",
                    dataType: "string",
                    description: ""
                }
            ]
        },
        {
            entityTableName: "bookings_placement_requests",
            description: "",
            dataFreshnessDays: 3,
            dataFreshnessDisableDuringRange: true,
            keys: [{
                keyName: "objectives",
                dataType: "string",
                description: ""
            }, {
                keyName: "urn",
                dataType: "string",
                description: ""
            }, {
                keyName: "degree_stage",
                dataType: "string",
                description: ""
            }, {
                keyName: "degree_subject",
                dataType: "string",
                description: ""
            }, {
                keyName: "teaching_stage",
                dataType: "string",
                description: ""
            }, {
                keyName: "subject_first_choice",
                dataType: "string",
                description: ""
            }, {
                keyName: "subject_second_choice",
                dataType: "string",
                description: ""
            }, {
                keyName: "has_dbs_check",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "availability",
                dataType: "string",
                description: ""
            }, {
                keyName: "bookings_placement_date_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_placement_dates"
            }, {
                keyName: "bookings_school_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_schools"
            }, {
                keyName: "bookings_subject_id",
                dataType: "string",
                description: ""
            }, {
                keyName: "analytics_tracking_uuid",
                dataType: "string",
                description: ""
            }, {
                keyName: "viewed_at",
                dataType: "timestamp",
                description: ""
            }, {
                keyName: "candidate_id",
                dataType: "string",
                description: "",
                hidden: true,
            }, {
                keyName: "under_consideration_at",
                dataType: "timestamp",
                description: ""
            }, {
                keyName: "experience_type",
                dataType: "string",
                description: ""
            }]
        },
        {
            entityTableName: "bookings_bookings",
            description: "",
            dataFreshnessDays: 3,
            dataFreshnessDisableDuringRange: true,
            keys: [{
                keyName: "date",
                dataType: "date",
                description: ""
            }, {
                keyName: "bookings_subject_id",
                dataType: "string",
                description: ""
            }, {
                keyName: "bookings_placement_request_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_placement_requests"
            }, {
                keyName: "bookings_school_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_schools"
            }, {
                keyName: "location",
                dataType: "string",
                description: ""
            }, {
                keyName: "duration",
                dataType: "integer",
                description: ""
            }, {
                keyName: "accepted_at",
                dataType: "timestamp",
                description: ""
            }, {
                keyName: "attended",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "experience_type",
                dataType: "string",
                description: ""
            }]
        },
        {
            entityTableName: "feedbacks",
            description: "",
            dataFreshnessDays: 7,
            dataFreshnessDisableDuringRange: true,
            keys: [{
                keyName: "rating",
                dataType: "string",
                description: ""
            }, {
                keyName: "improvements",
                dataType: "string",
                description: ""
            }, {
                keyName: "urn",
                dataType: "string",
                description: ""
            }, {
                keyName: "successful_visit",
                dataType: "boolean",
                description: ""
            }, {
                keyName: "referrer",
                dataType: "string",
                description: ""
            }, {
                keyName: "reason_for_using_service",
                dataType: "string",
                description: ""
            }, {
                keyName: "type",
                dataType: "string",
                description: ""
            }]
        },
        {
            entityTableName: "events",
            description: "",
            dataFreshnessDays: 6,
            dataFreshnessDisableDuringRange: true,
            keys: [{
                keyName: "bookings_school_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_schools"
            }, {
                keyName: "event_type",
                alias: "se_event_type",
                dataType: "string",
                description: ""
            }, {
                keyName: "recordable_id",
                dataType: "string",
                description: ""
            }, {
                keyName: "recordable_type",
                dataType: "string",
                description: ""
            }, {
                keyName: "bookings_candidate_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "bookings_candidates",
                hidden: true,
            }]
        }, {
            entityTableName: "users_roles",
            description: "",
            materialisation: "view",
            keys: [{
                keyName: "user_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "users",
                hidden: true,
            }, {
                keyName: "event_type",
                alias: "se_event_type",
                dataType: "string",
                description: ""
            }, {
                keyName: "role_id",
                dataType: "string",
                description: "",
                foreignKeyTable: "roles"
            }]
        }, {
            entityTableName: "roles",
            description: "",
            materialisation: "view",
            keys: [{
                keyName: "name",
                dataType: "string",
                description: ""
            }, {
                keyName: "resource_type",
                dataType: "string",
                description: ""
            }, {
                keyName: "resource_id",
                dataType: "string",
                description: ""
            }]
        }
    ]
});
